# Generated by Django 2.2 on 2020-07-21 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0008_auto_20200721_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tovar',
            name='desc',
            field=models.TextField(default='', error_messages={'required': 'Ошибка в поле описание'}, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tovar',
            name='name',
            field=models.CharField(default='', error_messages={'required': 'Ошибка в поле название'}, max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tovar',
            name='price',
            field=models.FloatField(error_messages={'required': 'Ошибка в поле цена'}, max_length=3, verbose_name='Цена'),
        ),
    ]
