# Generated by Django 2.2 on 2020-07-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0009_auto_20200721_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tovar',
            name='desc',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tovar',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tovar',
            name='price',
            field=models.FloatField(max_length=3, verbose_name='Цена'),
        ),
    ]
