# Generated by Django 2.2 on 2020-07-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0010_auto_20200722_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tovar',
            name='price',
            field=models.FloatField(error_messages='', max_length=3, verbose_name='Цена'),
        ),
    ]
