# Generated by Django 2.2 on 2020-07-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0011_auto_20200724_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tovar',
            name='price',
            field=models.FloatField(max_length=3, verbose_name='Цена'),
        ),
    ]
