# Generated by Django 2.2 on 2020-07-27 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0012_auto_20200724_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='tovar',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testsite.Category', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
