# Generated by Django 2.2 on 2020-07-27 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0013_tovar_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tovar',
            name='category',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='testsite.Category', verbose_name='Категория'),
        ),
    ]
