# Generated by Django 2.2 on 2020-07-28 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0014_auto_20200727_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tovar',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='testsite.Category', verbose_name='Категория'),
        ),
    ]
